import React from "react";

type Props = {};

export const customers = [
  {
    id: 1,
    fullname: "Rora Vuitton",
    email: "rvuitton0@hud.gov",
    about:
      "Driver of three-wheeled motor vehicle injured in collision with two- or three-wheeled motor vehicle in traffic accident, subsequent encounter",
    address: "12 Maple Way",
    gender: "Female",
    tel: "517-811-9232",
    avartar: "https://robohash.org/nobisfugitdolores.png?size=60x60&set=set1",
    created_at: "14/07/2022",
    updated_at: "11/07/2023",
  },
  {
    id: 2,
    fullname: "Vincents Olley",
    email: "volley1@sciencedaily.com",
    about:
      "Nondisplaced fracture of unspecified ulna styloid process, initial encounter for closed fracture",
    address: "0526 Lakewood Plaza",
    gender: "Male",
    tel: "588-670-1958",
    avartar: "https://robohash.org/saepealiasmolestiae.png?size=60x60&set=set1",
    created_at: "12/07/2022",
    updated_at: "28/06/2021",
  },
  {
    id: 3,
    fullname: "Titos Stockman",
    email: "tstockman2@who.int",
    about: "Abrasion of unspecified wrist, initial encounter",
    address: "2 Logan Lane",
    gender: "Male",
    tel: "669-940-4478",
    avartar: "https://robohash.org/officiamolestiashic.png?size=60x60&set=set1",
    created_at: "11/07/2021",
    updated_at: "21/04/2023",
  },
  {
    id: 4,
    fullname: "Talyah Tatham",
    email: "ttatham3@narod.ru",
    about: "Displaced transverse fracture of unspecified acetabulum",
    address: "5 Kennedy Avenue",
    gender: "Female",
    tel: "253-836-3624",
    avartar: "https://robohash.org/delectusharumquidem.png?size=60x60&set=set1",
    created_at: "05/12/2022",
    updated_at: "28/04/2022",
  },
  {
    id: 5,
    fullname: "Sephira Primarolo",
    email: "sprimarolo4@symantec.com",
    about: "Unspecified dislocation of left toe(s)",
    address: "37826 Cherokee Road",
    gender: "Female",
    tel: "772-529-9766",
    avartar: "https://robohash.org/estveritatisquia.png?size=60x60&set=set1",
    created_at: "21/03/2022",
    updated_at: "27/11/2022",
  },
  {
    id: 6,
    fullname: "Claiborn Libbis",
    email: "clibbis5@hao123.com",
    about:
      "Displaced unspecified fracture of unspecified great toe, subsequent encounter for fracture with malunion",
    address: "7470 Melby Center",
    gender: "Male",
    tel: "312-807-1393",
    avartar: "https://robohash.org/inatqueut.png?size=60x60&set=set1",
    created_at: "15/04/2022",
    updated_at: "05/12/2021",
  },
  {
    id: 7,
    fullname: "Teena Gumley",
    email: "tgumley6@usnews.com",
    about:
      "Other fractures of lower end of unspecified radius, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion",
    address: "06 Bartillon Road",
    gender: "Female",
    tel: "805-734-2816",
    avartar: "https://robohash.org/esteosnatus.png?size=60x60&set=set1",
    created_at: "15/12/2022",
    updated_at: "17/01/2022",
  },
  {
    id: 8,
    fullname: "Carri Whodcoat",
    email: "cwhodcoat7@pagesperso-orange.fr",
    about:
      "Drowning and submersion in natural water, undetermined intent, initial encounter",
    address: "65634 Starling Court",
    gender: "Female",
    tel: "709-920-8580",
    avartar: "https://robohash.org/vitaeatquesequi.png?size=60x60&set=set1",
    created_at: "23/06/2023",
    updated_at: "22/06/2023",
  },
  {
    id: 9,
    fullname: "Scottie Byrth",
    email: "sbyrth8@usnews.com",
    about:
      "Puncture wound with foreign body of vagina and vulva, initial encounter",
    address: "4 Moland Drive",
    gender: "Male",
    tel: "222-182-4106",
    avartar: "https://robohash.org/etcorruptiquia.png?size=60x60&set=set1",
    created_at: "18/05/2023",
    updated_at: "27/06/2021",
  },
  {
    id: 10,
    fullname: "Emmye Haddington",
    email: "ehaddington9@w3.org",
    about: "Other myositis, unspecified thigh",
    address: "18647 Russell Lane",
    gender: "Female",
    tel: "732-544-4904",
    avartar: "https://robohash.org/etrationeaut.png?size=60x60&set=set1",
    created_at: "16/12/2021",
    updated_at: "26/10/2022",
  },
  {
    id: 11,
    fullname: "Carena Simanek",
    email: "csimaneka@mayoclinic.com",
    about:
      "Person boarding or alighting a car injured in collision with sport utility vehicle, subsequent encounter",
    address: "9166 Golden Leaf Road",
    gender: "Female",
    tel: "513-540-2103",
    avartar:
      "https://robohash.org/laudantiumdoloresreprehenderit.png?size=60x60&set=set1",
    created_at: "01/08/2022",
    updated_at: "05/02/2023",
  },
  {
    id: 12,
    fullname: "Marve Redhills",
    email: "mredhillsb@chicagotribune.com",
    about: "Sarcoidosis of other sites",
    address: "65 Vera Avenue",
    gender: "Male",
    tel: "164-807-3153",
    avartar: "https://robohash.org/saepenondolorem.png?size=60x60&set=set1",
    created_at: "07/10/2021",
    updated_at: "04/10/2021",
  },
  {
    id: 13,
    fullname: "Guillaume Burgisi",
    email: "gburgisic@tinyurl.com",
    about: "Pyemic and septic embolism in pregnancy",
    address: "8348 Kropf Court",
    gender: "Male",
    tel: "394-919-9530",
    avartar: "https://robohash.org/quisaccusantiumet.png?size=60x60&set=set1",
    created_at: "02/10/2021",
    updated_at: "17/04/2023",
  },
  {
    id: 14,
    fullname: "Taddeusz Heak",
    email: "theakd@rediff.com",
    about:
      "Passenger injured in collision with other motor vehicles in traffic accident, subsequent encounter",
    address: "8968 Ridge Oak Junction",
    gender: "Male",
    tel: "267-334-4402",
    avartar: "https://robohash.org/quoipsumet.png?size=60x60&set=set1",
    created_at: "08/02/2022",
    updated_at: "22/01/2023",
  },
  {
    id: 15,
    fullname: "Murry Moreno",
    email: "mmorenoe@delicious.com",
    about: "Juvenile dermatopolymyositis, organ involvement unspecified",
    address: "45703 Coleman Pass",
    gender: "Male",
    tel: "160-382-8373",
    avartar: "https://robohash.org/nostrumnihilnisi.png?size=60x60&set=set1",
    created_at: "20/08/2021",
    updated_at: "16/04/2022",
  },
  {
    id: 16,
    fullname: "Itch Balch",
    email: "ibalchf@furl.net",
    about:
      "Military operations involving thermal radiation effect of nuclear weapon, military personnel, sequela",
    address: "3067 Twin Pines Alley",
    gender: "Male",
    tel: "888-864-0395",
    avartar: "https://robohash.org/autbeataedelectus.png?size=60x60&set=set1",
    created_at: "02/01/2022",
    updated_at: "09/01/2022",
  },
  {
    id: 17,
    fullname: "Feliza Coppin",
    email: "fcopping@altervista.org",
    about:
      "Age-related osteoporosis with current pathological fracture, vertebra(e), sequela",
    address: "45 Hauk Terrace",
    gender: "Female",
    tel: "751-148-0872",
    avartar: "https://robohash.org/quicorruptiullam.png?size=60x60&set=set1",
    created_at: "01/11/2022",
    updated_at: "01/05/2023",
  },
  {
    id: 18,
    fullname: "Tatum Marien",
    email: "tmarienh@comcast.net",
    about:
      "Nondisplaced fracture of first metatarsal bone, unspecified foot, initial encounter for open fracture",
    address: "0 Pine View Hill",
    gender: "Female",
    tel: "323-547-2754",
    avartar: "https://robohash.org/dolorquamut.png?size=60x60&set=set1",
    created_at: "07/09/2022",
    updated_at: "13/04/2022",
  },
  {
    id: 19,
    fullname: "Ahmad Filippello",
    email: "afilippelloi@t.co",
    about:
      "Laceration of muscle(s) and tendon(s) of the rotator cuff of shoulder",
    address: "0665 Ohio Way",
    gender: "Male",
    tel: "293-425-3281",
    avartar:
      "https://robohash.org/consecteturquidemsed.png?size=60x60&set=set1",
    created_at: "13/04/2022",
    updated_at: "21/04/2022",
  },
  {
    id: 20,
    fullname: "Ashien Winterton",
    email: "awintertonj@psu.edu",
    about: "Exposure of implanted ureteral bulking agent into ureter, sequela",
    address: "03 1st Court",
    gender: "Female",
    tel: "457-795-5946",
    avartar: "https://robohash.org/abessequidem.png?size=60x60&set=set1",
    created_at: "12/05/2022",
    updated_at: "23/11/2021",
  },
];

export const note = [
  {
    id: 1,
    customer_name: "Karyn Want",
    detail:
      "Triplet pregnancy, unable to determine number of placenta and number of amniotic sacs, unspecified trimester",
    title: "Kismet",
    category: "task",
    noted_date: "02/09/2023",
    updated_at: "03/06/2022",
  },
  {
    id: 2,
    customer_name: "Carley Dehmel",
    detail: "Blister (nonthermal), right thigh, subsequent encounter",
    title: "Zatoichi and the Chess Expert (Zatôichi Jigoku tabi) (Zatôichi 12)",
    category: "task",
    noted_date: "06/06/2022",
    updated_at: "12/06/2022",
  },
  {
    id: 3,
    customer_name: "Celeste Sommerly",
    detail:
      "Asphyxiation due to smothering under another person's body (in bed), assault, subsequent encounter",
    title: "Million Dollar Legs",
    category: "task",
    noted_date: "08/02/2023",
    updated_at: "01/06/2023",
  },
  {
    id: 4,
    customer_name: "Kristen Skarin",
    detail:
      "Injury of right internal carotid artery, intracranial portion, not elsewhere classified with loss of consciousness of 6 hours to 24 hours",
    title: "Masque of the Red Death, The",
    category: "task",
    noted_date: "20/06/2023",
    updated_at: "11/10/2021",
  },
  {
    id: 5,
    customer_name: "Xenia Moret",
    detail: "Fistula of bile duct",
    title: "River Wild, The",
    category: "task",
    noted_date: "09/12/2021",
    updated_at: "11/01/2022",
  },
  {
    id: 6,
    customer_name: "Stevana Phillpotts",
    detail: "Nondisplaced fracture of proximal phalanx of right little finger",
    title: "Civic Duty",
    category: "todo",
    noted_date: "21/01/2022",
    updated_at: "25/05/2022",
  },
  {
    id: 7,
    customer_name: "Neale Gommey",
    detail: "Anaphylactic reaction due to tree nuts and seeds",
    title: "Don Q Son of Zorro",
    category: "todo",
    noted_date: "08/04/2023",
    updated_at: "27/12/2021",
  },
  {
    id: 8,
    customer_name: "Ozzy Michallat",
    detail: "Bitten by horse, sequela",
    title: "Finding Fela!",
    category: "todo",
    noted_date: "21/06/2022",
    updated_at: "05/11/2022",
  },
  {
    id: 9,
    customer_name: "Stafford Gethings",
    detail: "Wedge compression fracture of first lumbar vertebra",
    title: "Hitler: A Film from Germany (Hitler - ein Film aus Deutschland)",
    category: "todo",
    noted_date: "24/03/2022",
    updated_at: "14/11/2021",
  },
  {
    id: 10,
    customer_name: "Corilla Boxe",
    detail:
      "Displaced fracture of proximal phalanx of right middle finger, initial encounter for open fracture",
    title: "Destiny Turns on the Radio",
    category: "todo",
    noted_date: "28/01/2022",
    updated_at: "11/06/2022",
  },
  {
    id: 11,
    customer_name: "Ernaline McCartney",
    detail:
      "Unstable burst fracture of unspecified thoracic vertebra, subsequent encounter for fracture with routine healing",
    title: "Groundstar Conspiracy, The",
    category: "appointment",
    noted_date: "13/08/2023",
    updated_at: "12/07/2023",
  },
  {
    id: 12,
    customer_name: "Blakelee Saxon",
    detail:
      "Displaced transverse fracture of unspecified patella, subsequent encounter for closed fracture with malunion",
    title:
      "Crying Out Love in the Center of the World (Sekai no chûshin de, ai o sakebu)",
    category: "appointment",
    noted_date: "01/09/2021",
    updated_at: "30/08/2022",
  },
  {
    id: 13,
    customer_name: "Sybyl Oldnall",
    detail:
      "Intraoperative and postprocedural complications and disorders of digestive system, not elsewhere classified",
    title: "Limuzins Janu nakts krasa",
    category: "appointment",
    noted_date: "28/08/2023",
    updated_at: "24/08/2022",
  },
  {
    id: 14,
    customer_name: "Joceline Watson-Brown",
    detail:
      "Toxic effect of hydrogen sulfide, intentional self-harm, initial encounter",
    title: "Careful",
    category: "appointment",
    noted_date: "08/07/2023",
    updated_at: "10/11/2022",
  },
  {
    id: 15,
    customer_name: "Booth Hyde-Chambers",
    detail:
      "Recurrent cholesteatoma of postmastoidectomy cavity, unspecified ear",
    title: "Under the Boardwalk: The Monopoly Story",
    category: "appointment",
    noted_date: "29/09/2023",
    updated_at: "22/04/2023",
  },
  {
    id: 16,
    customer_name: "Darb Wayper",
    detail:
      "Other infections with a predominantly sexual mode of transmission complicating pregnancy, third trimester",
    title: "Tarzan Escapes",
    category: "note",
    noted_date: "02/03/2022",
    updated_at: "18/08/2022",
  },
  {
    id: 17,
    customer_name: "Kelwin Camplin",
    detail: "Osteonecrosis due to previous trauma, other site",
    title: "In Old California",
    category: "note",
    noted_date: "11/10/2021",
    updated_at: "05/01/2022",
  },
  {
    id: 18,
    customer_name: "Davina Cordova",
    detail:
      "War operations involving chemical weapons and other forms of unconventional warfare, civilian",
    title: "LEGO DC Comics Super Heroes: Justice League vs. Bizarro League",
    category: "note",
    noted_date: "21/08/2022",
    updated_at: "25/08/2022",
  },
  {
    id: 19,
    customer_name: "Heindrick Strank",
    detail:
      "Unspecified traumatic spondylolisthesis of sixth cervical vertebra",
    title: "Platinum Blonde",
    category: "note",
    noted_date: "15/11/2021",
    updated_at: "25/12/2021",
  },
  {
    id: 20,
    customer_name: "Thekla Scobbie",
    detail: "Temporary auditory threshold shift, left ear",
    title: "Strait-Jacket",
    category: "note",
    noted_date: "16/03/2023",
    updated_at: "12/08/2022",
  },
];
