import React from "react";

type Props = {};

export const customers = [
  {
    id: 1,
    name: "Starr Marini",
    email: "smarini0@plala.or.jp",
    gender: "Female",
    address: "Suite 88",
    tel: "771 194 0534",
    avartar: "https://robohash.org/quiarerumdolorem.png?size=50x50&set=set1",
  },
  {
    id: 2,
    name: "Felita Cummings",
    email: "fcummings1@blogtalkradio.com",
    gender: "Female",
    address: "Suite 13",
    tel: "853 343 6943",
    avartar: "https://robohash.org/nihilquiaet.png?size=50x50&set=set1",
  },
  {
    id: 3,
    name: "Hali Sommerscales",
    email: "hsommerscales2@engadget.com",
    gender: "Female",
    address: "3rd Floor",
    tel: "175 183 6797",
    avartar:
      "https://robohash.org/inventoredistinctionulla.png?size=50x50&set=set1",
  },
  {
    id: 4,
    name: "Audi Chat",
    email: "achat3@fastcompany.com",
    gender: "Female",
    address: "Suite 22",
    tel: "328 380 9809",
    avartar: "https://robohash.org/seddoloribusnam.png?size=50x50&set=set1",
  },
  {
    id: 5,
    name: "Raleigh Whitloe",
    email: "rwhitloe4@noaa.gov",
    gender: "Male",
    address: "Suite 81",
    tel: "991 256 9075",
    avartar: "https://robohash.org/etfugitiusto.png?size=50x50&set=set1",
  },
  {
    id: 6,
    name: "Birgitta Launder",
    email: "blaunder5@discovery.com",
    gender: "Female",
    address: "Apt 211",
    tel: "832 823 3016",
    avartar:
      "https://robohash.org/consequunturoccaecatiut.png?size=50x50&set=set1",
  },
  {
    id: 7,
    name: "Editha Govenlock",
    email: "egovenlock6@about.com",
    gender: "Female",
    address: "Apt 1953",
    tel: "891 495 6179",
    avartar:
      "https://robohash.org/reruminciduntdeleniti.png?size=50x50&set=set1",
  },
  {
    id: 8,
    name: "Jacky Cridlan",
    email: "jcridlan7@earthlink.net",
    gender: "Male",
    address: "Room 499",
    tel: "816 581 3796",
    avartar:
      "https://robohash.org/culpanecessitatibusofficia.png?size=50x50&set=set1",
  },
  {
    id: 9,
    name: "Vivianne Durak",
    email: "vdurak8@typepad.com",
    gender: "Female",
    address: "Apt 1520",
    tel: "353 985 6300",
    avartar: "https://robohash.org/quisplaceatrerum.png?size=50x50&set=set1",
  },
  {
    id: 10,
    name: "Lexis Rigardeau",
    email: "lrigardeau9@wunderground.com",
    gender: "Female",
    address: "Apt 416",
    tel: "544 277 6437",
    avartar: "https://robohash.org/culpaquilaboriosam.png?size=50x50&set=set1",
  },
  {
    id: 11,
    name: "Hamil Verrill",
    email: "hverrilla@dell.com",
    gender: "Male",
    address: "Suite 1",
    tel: "466 626 3427",
    avartar: "https://robohash.org/quiaquaeratiure.png?size=50x50&set=set1",
  },
  {
    id: 12,
    name: "Pavlov Redier",
    email: "predierb@who.int",
    gender: "Male",
    address: "PO Box 88627",
    tel: "826 123 5038",
    avartar: "https://robohash.org/autemsolutasaepe.png?size=50x50&set=set1",
  },
  {
    id: 13,
    name: "Chan Canada",
    email: "ccanadac@yahoo.com",
    gender: "Male",
    address: "PO Box 87876",
    tel: "354 830 6172",
    avartar: "https://robohash.org/uteosquia.png?size=50x50&set=set1",
  },
  {
    id: 14,
    name: "Suzette Glastonbury",
    email: "sglastonburyd@wp.com",
    gender: "Female",
    address: "Suite 47",
    tel: "270 887 8125",
    avartar:
      "https://robohash.org/molestiaspraesentiummolestiae.png?size=50x50&set=set1",
  },
  {
    id: 15,
    name: "Dougy Crippes",
    email: "dcrippese@oakley.com",
    gender: "Male",
    address: "Suite 87",
    tel: "119 910 8320",
    avartar: "https://robohash.org/modiblanditiiset.png?size=50x50&set=set1",
  },
  {
    id: 16,
    name: "Christi Turbill",
    email: "cturbillf@google.com.hk",
    gender: "Female",
    address: "PO Box 58735",
    tel: "266 722 2996",
    avartar:
      "https://robohash.org/laboriosamutcupiditate.png?size=50x50&set=set1",
  },
  {
    id: 17,
    name: "Tate Trundle",
    email: "ttrundleg@nba.com",
    gender: "Male",
    address: "Suite 14",
    tel: "862 473 5877",
    avartar: "https://robohash.org/etsedmollitia.png?size=50x50&set=set1",
  },
  {
    id: 18,
    name: "Letitia Burne",
    email: "lburneh@webnode.com",
    gender: "Agender",
    address: "Room 1232",
    tel: "800 943 1545",
    avartar: "https://robohash.org/quidoloremagnam.png?size=50x50&set=set1",
  },
  {
    id: 19,
    name: "Fitzgerald Tweedle",
    email: "ftweedlei@loc.gov",
    gender: "Male",
    address: "Suite 84",
    tel: "332 729 1670",
    avartar: "https://robohash.org/quasisequilaborum.png?size=50x50&set=set1",
  },
  {
    id: 20,
    name: "Viv Lowfill",
    email: "vlowfillj@bbb.org",
    gender: "Genderqueer",
    address: "PO Box 86823",
    tel: "145 885 2184",
    avartar: "https://robohash.org/architectoutaliquam.png?size=50x50&set=set1",
  },
];

export const note = [
  {
    id: 1,
    title: "Professor",
    note_detail:
      "Type 2 diab w mild nonprlf diabetic rtnop w macular edema testdddddddddddddddddddddddddddddddddddddddddddddddddddddd",
    category: "task",

    customer_name: "Sherm Chinge",
    updated_at: "20-09-2023",
    noted_date: "06-12-2022",
  },
  {
    id: 2,
    title: "Research Associate",
    note_detail: "Toxic effect of hydrogen sulfide, undetermined, subs encntr",
    category: "task",

    customer_name: "Clair Gatheral",
    updated_at: "27-03-2023",
    noted_date: "11-07-2023",
  },
  {
    id: 3,
    title: "Account Representative IV",
    note_detail: "Pnctr w/o fb of abd wall, r upper q w penet perit cav, sqla",
    category: "appointment",

    customer_name: "Sandie Stoute",
    updated_at: "02-10-2023",
    noted_date: "04-03-2023",
  },
  {
    id: 4,
    title: "Design Engineer",
    note_detail: "Burn of first degree of left ankle",
    category: "appointment",

    customer_name: "Marney Teall",
    updated_at: "05-07-2023",
    noted_date: "28-02-2023",
  },
  {
    id: 5,
    title: "Programmer Analyst I",
    note_detail: "Unstable burst fracture of T7-T8 vertebra",
    category: "appointment",

    customer_name: "Michaelina Coe",
    updated_at: "21-05-2023",
    noted_date: "16-10-2023",
  },
  {
    id: 6,
    title: "Financial Analyst",
    note_detail: "Puncture wound with foreign body of unspecified ear",
    category: "appointment",

    customer_name: "Dorthy Mockford",
    updated_at: "30-01-2023",
    noted_date: "08-08-2023",
  },
  {
    id: 7,
    title: "Senior Sales Associate",
    note_detail: "Scarring of conjunctiva, unspecified eye",
    category: "task",

    customer_name: "Donny Keirl",
    updated_at: "07-05-2023",
    noted_date: "04-12-2022",
  },
  {
    id: 8,
    title: "Professor",
    note_detail: "Toxic effects of chloroform",
    category: "todo",

    customer_name: "Frederic Snodden",
    updated_at: "30-10-2023",
    noted_date: "13-07-2023",
  },
  {
    id: 9,
    title: "Electrical Engineer",
    note_detail: "Adverse effect of iron and its compounds, sequela",
    category: "task",

    customer_name: "Kiel Petruskevich",
    updated_at: "08-05-2023",
    noted_date: "18-11-2022",
  },
  {
    id: 10,
    title: "Social Worker",
    note_detail: "Burn of unspecified degree of right shoulder, sequela",
    category: "note",

    customer_name: "Iona Leopard",
    updated_at: "03-08-2023",
    noted_date: "26-06-2023",
  },
  {
    id: 11,
    title: "Senior Cost Accountant",
    note_detail: "Oth symptoms and signs involving the dgstv sys and abdomen",
    category: "note",

    customer_name: "Leicester Kenneway",
    updated_at: "03-01-2023",
    noted_date: "26-04-2023",
  },
  {
    id: 12,
    title: "Media Manager II",
    note_detail: "Path fx in oth disease, r ankle, subs for fx w routn heal",
    category: "note",

    customer_name: "Aubry Janway",
    updated_at: "06-12-2022",
    noted_date: "28-08-2023",
  },
  {
    id: 13,
    title: "Financial Advisor",
    note_detail: "Schizophreniform disorder",
    category: "note",

    customer_name: "Reuben Gamwell",
    updated_at: "13-12-2022",
    noted_date: "13-06-2023",
  },
  {
    id: 14,
    title: "Tax Accountant",
    note_detail: "Nodular episcleritis, left eye",
    category: "note",

    customer_name: "Courtenay Orritt",
    updated_at: "20-05-2023",
    noted_date: "11-06-2023",
  },
  {
    id: 15,
    title: "Financial Advisor",
    note_detail: "Poisn by oth agents prim acting on the resp sys, undet, init",
    category: "task",

    customer_name: "Ivonne Saterthwait",
    updated_at: "15-06-2023",
    noted_date: "19-11-2022",
  },
  {
    id: 16,
    title: "Research Nurse",
    note_detail: "Nodular sclerosis Hodgkin lymphoma, intrapelvic lymph nodes",
    category: "task",

    customer_name: "Lin Matuskiewicz",
    updated_at: "13-12-2022",
    noted_date: "23-09-2023",
  },
  {
    id: 17,
    title: "Civil Engineer",
    note_detail: "Foreign body in vulva and vagina",
    category: "task",

    customer_name: "Ailsun Rizzi",
    updated_at: "02-10-2023",
    noted_date: "08-07-2023",
  },
  {
    id: 18,
    title: "Account Executive",
    note_detail: "Milt op involving fragments from munitions, milt, subs",
    category: "todo",

    customer_name: "Serge Yve",
    updated_at: "28-10-2023",
    noted_date: "14-05-2023",
  },
  {
    id: 19,
    title: "Nurse ",
    note_detail: "Poisoning by inhaled anesthetics, assault, initial encounter",
    category: "appointment",

    customer_name: "Hamil Melato",
    updated_at: "30-07-2023",
    noted_date: "30-01-2023",
  },
  {
    id: 20,
    title: "Software ",
    note_detail: "Corros 10-19% of body surface w 0% to 9% third degree corros",
    category: "todo",

    customer_name: "Steffane Emmins",
    updated_at: "16-12-2022",
    noted_date: "04-06-2023",
  },
];
